FiBiNET_base:
    model: FiBiNET
    dataset_id: TBD
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    hidden_units: [500, 500, 500]
    hidden_activations: relu
    bilinear_type: field_interaction
    reduction_ratio: 3
    embedding_dropout: 0
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

FiBiNET_criteo_x4:
    model: FiBiNET
    dataset_id: criteo_x4
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    hidden_units: [500, 500, 500]
    hidden_activations: relu
    bilinear_type: field_interaction
    reduction_ratio: 3
    embedding_dropout: 0
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

FiBiNET_avazu_x4:
    model: FiBiNET
    dataset_id: avazu_x4
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    hidden_units: [500, 500, 500]
    hidden_activations: relu
    bilinear_type: field_interaction
    reduction_ratio: 3
    embedding_dropout: 0
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

FiBiNET_kkbox_x4:
    model: FiBiNET
    dataset_id: kkbox_x4
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    hidden_units: [500, 500, 500]
    hidden_activations: relu
    bilinear_type: field_interaction
    reduction_ratio: 3
    embedding_dropout: 0
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
