FiGNN_base:
    model: FiGNN
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    gnn_layers: 3
    use_residual: True
    use_gru: True
    reuse_graph_layer: False
    embedding_dropout: 0
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

FiGNN_criteo_x4:
    model: FiGNN
    dataset_id: criteo_x4
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    gnn_layers: 3
    use_residual: True
    use_gru: True
    reuse_graph_layer: False
    embedding_dropout: 0
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

FiGNN_avazu_x4:
    model: FiGNN
    dataset_id: avazu_x4
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    gnn_layers: 3
    use_residual: True
    use_gru: True
    reuse_graph_layer: False
    embedding_dropout: 0
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

FiGNN_kkbox_x4:
    model: FiGNN
    dataset_id: kkbox_x4
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    gnn_layers: 3
    use_residual: True
    use_gru: True
    reuse_graph_layer: False
    embedding_dropout: 0
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'