MF_base:
    model: MF
    dataset_id: TBD
    metrics: ['Recall(k=20)', 'Recall(k=50)', 'NDCG(k=20)', 'NDCG(k=50)', 'HitRate(k=20)', 'HitRate(k=50)']
    optimizer: adam
    learning_rate: 1.0e-3
    num_negs: 20
    regularizer: 0
    batch_size: 1024
    embedding_dim: 64
    embedding_dropout: 0
    similarity_score: dot
    loss: PairwiseLogisticLoss
    margin: 1
    negative_weight: null
    sampling_num_process: 1
    fix_sampling_seeds: True
    ignore_pos_items: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: 'Recall(k=20)'
    monitor_mode: 'max'