YoutubeDNN_base:
    model: YoutubeDNN
    dataset_id: TBD
    margin: 1
    metrics: ['Recall(k=20)', 'Recall(k=50)', 'NDCG(k=20)', 'NDCG(k=50)', 'HitRate(k=20)', 'HitRate(k=50)']
    optimizer: adam
    learning_rate: 1.0e-3
    batch_size: 1024
    num_negs: 20
    embedding_dim: 64
    output_dim: 64
    user_hidden_units: [64]
    user_hidden_activations: ReLU
    user_final_activation: null
    embedding_regularizer: 0
    net_regularizer: 0
    embedding_dropout: 0
    net_dropout: 0
    similarity_score: dot
    loss: SoftmaxCrossEntropyLoss
    negative_weight: null
    sampling_num_process: 1
    fix_sampling_seeds: True
    ignore_pos_items: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: 'Recall(k=20)'
    monitor_mode: 'max'