base_config: ../config/
base_expid: MF_base
dataset_id: yelp18_x0

dataset_config:
    yelp18_x0:
        data_root: ../data/Yelp18/
        data_format: csv
        train_data: ../data/Yelp18/yelp18_x0/train.csv
        valid_data: ../data/Yelp18/yelp18_x0/test.csv
        item_corpus: ../data/Yelp18/yelp18_x0/item_corpus.csv
        min_categr_count: 1
        query_index: query_index
        corpus_index: corpus_index
        feature_cols:
            - {'name': 'query_index', 'active': True, 'dtype': int, 'type': 'index'}
            - {'name': 'corpus_index', 'active': True, 'dtype': int, 'type': 'index'}
            - {'name': 'user_id', 'active': True, 'dtype': str, 'type': 'categorical', 'source': 'user'}
            - {'name': 'item_id', 'active': True, 'dtype': str, 'type': 'categorical', 'source': 'item'}
        label_col: {name: label, dtype: float}


tuner_space:
    model_root: './Yelp18/MF_CCL_yelp18_x0/'
    learning_rate: 1.e-4
    embedding_dim: 64
    embedding_dropout: 0.1
    num_negs: [800]
    regularizer: 1.e-9
    similarity_score: cosine
    loss: CosineContrastiveLoss
    negative_weight: 150
    margin: 0.9
    batch_size: 512
    seed: 2019
    monitor: Recall(k=20)
